name: PunkApi AWS Consumer CI/CD
on: [push]

jobs:
  Build:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Init
        run: make init ENV=test
      - name: install python requirements
        run: pip3 install -r aws_lambda/requirements.txt --upgrade
      - name: Make Tests
        run: make tests
      - name: Zip Lambda Function
        run: make zip_lambda_function
      - name: Make Plan
        run: make plan ENV=test

  Deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Init
        run: make init ENV=test
      - name: Make Apply
        run: make apply ENV=test