name: PunkApi AWS Consumer CI/CD
on:
  push:
    branches:
      - 'master'

jobs:
  CI-CD-Pipeline:
    name: Build Artifact
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v2
      - name: Make Init
        run: make init ENV=test
      - name: Upgrade pip and setuptools
        run: pip3 install setuptools pip --upgrade
      - name: Install python requirements.txt
        run: pip3 install -r aws_lambda/requirements.txt --upgrade
      - name: Perform Tests
        run: make tests
      - name: Zip Lambda Function
        run: make zip_lambda_function
      - name: Make Plan
        run: make plan ENV=test
      - name: Deploy
        run: make apply
